package com.dao.template;


import com.dao.DSqlAdmin;


public class DSqlTemplate extends DSqlAdmin {
 
    //template category  in here
      public final String SQL_TEMPLATE_TYPE_SELECT_ALL = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + ORDER_BY + TEMPLATE_CATEGORY_NAME;
      public final String SQL_TEMPLATE_TYPE_SELECT_SINGLE_ROW = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + WHERE + TEMPLATE_CATEGORY_ID + EQUAL + QUESTION;
      public final String SQL_TEMPLATE_TYPE_ADD_NEW = INSERT_INTO + TABLE_TEMPLATE_CATEGORY + FIELDS(TEMPLATE_TYPE_ALL_FIELDS,true)+ VALUES(TEMPLATE_TYPE_ALL_FIELDS.length);
      public final String SQL_TEMPLATE_TYPE_UPDATE = UPDATE + TABLE_TEMPLATE_CATEGORY + SET + SETS(TEMPLATE_TYPE_ALL_FIELDS)+ WHERE + TEMPLATE_CATEGORY_ID + EQUAL + QUESTION;
      public final String SQL_TEMPLATE_TYPE_CHECK_NAME = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + WHERE + TEMPLATE_CATEGORY_NAME + EQUAL + QUESTION;
      public final String SQL_TEMPLATE_TYPE_CHECK_NAME_ID = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + WHERE + TEMPLATE_CATEGORY_NAME + EQUAL + QUESTION + AND + TEMPLATE_CATEGORY_ID + DIFF + QUESTION;
      public final String SQL_TEMPLATE_TYPE_CHECK_CODE_ID = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + WHERE + TEMPLATE_CATEGORY_CODE + EQUAL + QUESTION + AND + TEMPLATE_CATEGORY_ID + DIFF + QUESTION;   
      public final String SQL_TEMPLATE_TYPE_SELECT_BY_ID = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + WHERE + TEMPLATE_CATEGORY_ID + EQUAL + QUESTION;
      public final String SQL_TEMPLATE_TYPE_CHECK_CODE = SELECT + STAR + FROM + TABLE_TEMPLATE_CATEGORY + WHERE + TEMPLATE_CATEGORY_CODE + EQUAL + QUESTION;
      
    //TEMPLATE
     public final String SQL_ALL_TEMPLATE_SEARCH= " SELECT TEMPLATES.*,USERS.FULLNAME,TEMPLATE_CATEGORY.NAME AS NAME_CATEGORY,DEPARTMENT.NAME AS DEP_NAME,DEPARTMENT.DEPARTMENT_ID AS DEPARTMENT_ID FROM TEMPLATES  LEFT JOIN USERS ON TEMPLATES.USER_ID=USERS.USER_ID  LEFT JOIN DEPARTMENT ON DEPARTMENT.DEPARTMENT_ID=TEMPLATES.DEPARTMENT_ID  LEFT JOIN TEMPLATE_CATEGORY ON TEMPLATE_CATEGORY.CATEGORY_ID=TEMPLATES.TEMPLATE_TYPE_ID WHERE  1=1 " ;
    public final String SQL_TEMPLATE_CHECK_CODE_UPDATE = SELECT +  TEMPLATE_NAME + FROM + TABLE_TEMPLATES  +  WHERE +  TEMPLATE_ID +  IN + OPEN + SELECT +  TEMPLATE_ID +  FROM +  TABLE_TEMPLATES +  WHERE +  TEMPLATE_ID + DIFF +QUESTION + CLOSE +  AND +  TEMPLATE_NAME + EQUAL + QUESTION;
    public final String SQL_GET_BY_CODE=SELECT + STAR + FROM + TABLE_TEMPLATES + WHERE + TEMPLATE_CODE + EQUAL + QUESTION + AND + TEMPLATE_PERMISSION + EQUAL + QUESTION;
    public final String   SQL_SELECT_TEMPLATE_BY_ID=SELECT+ STAR + FROM + TABLE_TEMPLATES + WHERE + TEMPLATE_ID + EQUAL + QUESTION;
    public final String   SQL_INSERT_TEMPLATE=INSERT_INTO + TABLE_TEMPLATES + FIELDS(TEMPLATE_ALL_FIELDS,true) + VALUES(TEMPLATE_ALL_FIELDS.length);
    public final String    SQL_UPDATE_TEMPLATE=UPDATE + TABLE_TEMPLATES + SET + SETS(TEMPLATE_ALL_FIELDS) + WHERE + TEMPLATE_ID + EQUAL + QUESTION;
    public final String  SQL_SELECT_ALL_TEMPLATE=SELECT + TABLE_USERS + STOP + USERS_FULLNAME + COMMA +TABLE_TEMPLATES+ STOP+ STAR +  FROM +  TABLE_TEMPLATES + LEFT_JOIN + TABLE_USERS +  ON + TABLE_TEMPLATES + STOP +TEMPLATE_USER_ID + EQUAL  + TABLE_USERS+STOP+USERS_USER_ID;
    public final String  SQL_SELECT_PRIVATE_STORE= "SELECT TEMPLATES.*,USERS.FULLNAME,TEMPLATE_CATEGORY.NAME AS NAME_CATEGORY,DEPARTMENT.NAME AS DEP_NAME FROM TEMPLATES LEFT JOIN USERS ON TEMPLATES.USER_ID=USERS.USER_ID LEFT JOIN DEPARTMENT ON DEPARTMENT.DEPARTMENT_ID=TEMPLATES.DEPARTMENT_ID LEFT JOIN TEMPLATE_CATEGORY ON TEMPLATE_CATEGORY.CATEGORY_ID=TEMPLATES.TEMPLATE_TYPE_ID ";
    public final String  SQL_SELECT_ADD_ADMIN_TEMPLATE="SELECT DISTINCT(CATEGORY_ID) FROM TEMPLATE_CATEGORY_ADMIN WHERE USER_ID=?";
    public final String  SQL_TEMPLATE_PERMISION=UPDATE + TABLE_TEMPLATES +   SET +   TEMPLATE_PERMISSION + EQUAL + QUESTION +  WHERE +  TEMPLATE_ID + EQUAL + QUESTION;
    


}
