package com.inf.tasks;




public interface IFieldsTasks {
     
    //  SET OF FIELDS ON CATEGORIES TABLES
    public final String TASK_CATEGORIES_CATEGORY_ID ="CATEGORY_ID";
    public final String TASK_CATEGORIES_CREATOR ="CREATOR";
    public final String TASK_CATEGORIES_TIMECREATE ="TIMECREATE";
    public final String TASK_CATEGORIES_TITLE ="TITLE";
    public final String TASK_CATEGORIES_DESCRIPTION ="DESCRIPTION";
    public final String TASK_CATEGORIES_BLOCK="BLOCK";
    public final String[] TASK_CATEGORIES_ALL_FIELDS ={TASK_CATEGORIES_CREATOR,TASK_CATEGORIES_TIMECREATE,TASK_CATEGORIES_TITLE,TASK_CATEGORIES_DESCRIPTION,TASK_CATEGORIES_BLOCK};
    
    //  SET OF FIELDS ON PROPLEMS TABLES
    public final String TASK_PROBLEMS_PROBLEM_ID ="PROBLEM_ID";
    public final String TASK_PROBLEMS_CREATOR ="CREATOR";
    public final String TASK_PROBLEMS_TITLE ="TITLE";
    public final String TASK_PROBLEMS_PROBLEM ="PROBLEM";
    public final String TASK_PROBLEMS_TIMECREATE ="TIMECREATE";
    public final String TASK_PROBLEMS_FILE ="FILES";
    public final String TASK_PROBLEMS_COMPLETE ="COMPLETE";
    public final String TASK_PROBLEMS_ROOT ="ROOT";
    public final String TASK_PROBLEMS_FROMDATE ="FROMDATE";
    public final String TASK_PROBLEMS_TODATE ="TODATE";
    public final String TASK_PROBLEMS_CATEGORY_ID ="CATEGORY_ID";
    public final String TASK_PROBLEMS_STOP ="STOP";
    public final String TASK_PROBLEMS_PATH_FILE ="PATH_FILE";
    public final String TASK_PROBLEMS_ACTIVE_REPORT ="ACTIVE_REPORT";
    
    public final String[] TASK_PROBLEMS_ALL_FIELDS ={TASK_PROBLEMS_CREATOR,TASK_PROBLEMS_TITLE,TASK_PROBLEMS_PROBLEM,TASK_PROBLEMS_TIMECREATE,TASK_PROBLEMS_FILE,TASK_PROBLEMS_COMPLETE,TASK_PROBLEMS_ROOT,TASK_PROBLEMS_FROMDATE,TASK_PROBLEMS_TODATE,TASK_PROBLEMS_CATEGORY_ID,TASK_PROBLEMS_STOP,TASK_PROBLEMS_PATH_FILE};
    
    //  SET OF FIELDS ON ASSIGN TABLES
    public final String TASK_ASSIGN_ASSIGN_ID   ="ASSIGN_ID";
    public final String TASK_ASSIGN_PROPLEM_ID  ="PROPLEM_ID";
    public final String TASK_ASSIGN_WORKER      ="WORKER";
    public final String TASK_ASSIGN_READ ="READED";
    public final String TASK_ASSIGN_ACCEPTED ="ACCEPTED";    
    public final String TASK_ASSIGN_COMPLETE ="COMPLETE";
    public final String TASK_ASSIGN_INCHARGE ="INCHARGE";
    public final String TASK_ASSIGN_TIMEASSIGN ="TIMEASSIGN";    
    public final String TASK_ASSIGN_STOP ="STOP";
    public final String TASK_ASSIGN_HAVE_REPORT ="HAVE_REPORT";
    public final String TASK_ASSIGN_ASSIGN_HAVE_REPORT ="ASSIGN_HAVE_REPORT";
    
    public final String[] TASK_ASSIGN_ALL_FIELDS ={TASK_ASSIGN_PROPLEM_ID,TASK_ASSIGN_WORKER,TASK_ASSIGN_READ,TASK_ASSIGN_ACCEPTED,TASK_ASSIGN_COMPLETE,TASK_ASSIGN_INCHARGE,TASK_ASSIGN_TIMEASSIGN,TASK_ASSIGN_STOP,TASK_ASSIGN_HAVE_REPORT};
    
    //  SET OF FIELDS ON REPORTS TABLES
    public final String TASK_REPORTS_REPORT_ID        = "ID";
    public final String TASK_REPORTS_ASSIGN_ID        = "ASSIGN_ID";
    public final String TASK_REPORTS_REPORT           = "REPORT";
    public final String TASK_REPORTS_TIMEREPORT       = "TIMEREPORT";
    public final String TASK_REPORTS_FILE             = "FILES";  
    public final String TASK_REPORTS_COMPLETE         = "COMPLETE"; 
    public final String TASK_REPORTS_PATH_FILE        = "PATH_FILE"; 
    public final String TASK_REPORTS_PROBLEM_ID       = "PROBLEM_ID"; 
    public final String TASK_REPORTS_CREATOR          = "CREATOR";
    public final String TASK_REPORTS_EMPS          = "EMPS";
    
    public final String[] TASK_REPORTS_ALL_FIELDS ={TASK_REPORTS_ASSIGN_ID,TASK_REPORTS_REPORT,TASK_REPORTS_TIMEREPORT,TASK_REPORTS_FILE,TASK_REPORTS_COMPLETE,TASK_REPORTS_PATH_FILE,TASK_REPORTS_PROBLEM_ID,TASK_REPORTS_CREATOR,TASK_REPORTS_EMPS};
    
    
}
