package com.inf.doc;

import com.inf.admin.IFieldsAdmin;

public interface IFieldsDoc extends IFieldsAdmin {

    //  SET OF FIELDS ON DOC_TRAILER_RECV TABLES
    public final String DOC_TRAILER_RECV_DOC_ID ="DOC_ID";
    public final String DOC_TRAILER_RECV_USERSEND_ID ="USERSEND_ID";   
    public final String DOC_TRAILER_RECV_READED ="READED";
    public final String DOC_TRAILER_RECV_TIMESEND ="TIMESEND";
    public final String DOC_TRAILER_RECV_FORYOU_ID ="FORYOU_ID";
    public final String DOC_TRAILER_RECV_USERRECV_ID ="USERRECV_ID";
    public final String DOC_TRAILER_RECV_VIEWS="VIEWS";    
    public final String DOC_TRAILER_RECV_DOCSTATUS="DOCSTATUS";    
    public final String DOC_TRAILER_RECV_BLOCK="BLOCK";    
    public final String[] DOC_TRAILER_RECV_ALL_FIELDS ={DOC_TRAILER_RECV_DOC_ID,DOC_TRAILER_RECV_USERSEND_ID,DOC_TRAILER_RECV_READED,DOC_TRAILER_RECV_TIMESEND,DOC_TRAILER_RECV_FORYOU_ID,DOC_TRAILER_RECV_VIEWS,DOC_TRAILER_RECV_DOCSTATUS,DOC_TRAILER_RECV_BLOCK,DOC_TRAILER_RECV_USERRECV_ID};
    
    //  SET OF FIELDS ON DOC_TRAILER_RECV TABLES
    public final String DOC_TRAILER_SEND_DOC_ID ="DOC_ID";
    public final String DOC_TRAILER_SEND_USERSEND_ID ="USERSEND_ID";   
    public final String DOC_TRAILER_SEND_READED ="READED";
    public final String DOC_TRAILER_SEND_TIMESEND ="TIMESEND";
    public final String DOC_TRAILER_SEND_FORYOU_ID ="FORYOU_ID";
    public final String DOC_TRAILER_SEND_USERRECV_ID ="USERRECV_ID";
    public final String DOC_TRAILER_SEND_VIEWS="VIEWS";
    public final String DOC_TRAILER_SEND_DOCSTATUS="DOCSTATUS";    
    public final String DOC_TRAILER_SEND_BLOCK="BLOCK";    
    public final String[] DOC_TRAILER_SEND_ALL_FIELDS ={DOC_TRAILER_SEND_DOC_ID,DOC_TRAILER_SEND_USERSEND_ID,DOC_TRAILER_SEND_READED,DOC_TRAILER_SEND_TIMESEND,DOC_TRAILER_SEND_FORYOU_ID,DOC_TRAILER_SEND_VIEWS,DOC_TRAILER_SEND_DOCSTATUS,DOC_TRAILER_SEND_BLOCK,DOC_TRAILER_SEND_USERRECV_ID};
    
    
    //  SET OF FIELDS ON DOC_REVIEW_RECV TABLES
    public final String DOC_REVIEW_RECV_REVIEW_ID ="REVIEW_ID";
    public final String DOC_REVIEW_RECV_DOC_ID ="DOC_ID";
    public final String DOC_REVIEW_RECV_CREATOR ="CREATOR";
    public final String DOC_REVIEW_RECV_TIMECREATE ="TIMECREATE";
    public final String DOC_REVIEW_RECV_TITLE ="TITLE";
    public final String DOC_REVIEW_RECV_ISSUE ="ISSUE";
    public final String DOC_REVIEW_RECV_FORYOU_CREATOR ="FORYOU_CREATOR";
    public final String DOC_REVIEW_RECV_DEADLINE="DEADLINE";
    public final String DOC_REVIEW_RECV_REVIEW_IDS="REVIEW_IDS";
    
    public final String[] DOC_REVIEW_RECV_ALL_FIELDS ={DOC_REVIEW_RECV_DOC_ID,DOC_REVIEW_RECV_CREATOR,DOC_REVIEW_RECV_TIMECREATE,DOC_REVIEW_RECV_TITLE,DOC_REVIEW_RECV_ISSUE,DOC_REVIEW_RECV_FORYOU_CREATOR,DOC_REVIEW_RECV_DEADLINE,DOC_REVIEW_RECV_REVIEW_IDS};
    
            
        //  SET OF FIELDS ON DOC_REVIEW_SEND TABLES
        public final String DOC_REVIEW_SEND_REVIEW_ID ="REVIEW_ID";
        public final String DOC_REVIEW_SEND_DOC_ID ="DOC_ID";
        public final String DOC_REVIEW_SEND_CREATOR ="CREATOR";
        public final String DOC_REVIEW_SEND_TIMECREATE ="TIMECREATE";
        public final String DOC_REVIEW_SEND_TITLE ="TITLE";
        public final String DOC_REVIEW_SEND_ISSUE ="ISSUE";
        public final String DOC_REVIEW_SEND_FORYOU_CREATOR ="FORYOU_CREATOR";
        public final String DOC_REVIEW_SEND_DEADLINE ="DEADLINE";
        public final String DOC_REVIEW_SEND_REVIEW_IDS ="REVIEW_IDS";
    
        public final String[] DOC_REVIEW_SEND_ALL_FIELDS ={DOC_REVIEW_SEND_DOC_ID,DOC_REVIEW_SEND_CREATOR,DOC_REVIEW_SEND_TIMECREATE,DOC_REVIEW_SEND_TITLE,DOC_REVIEW_SEND_ISSUE,DOC_REVIEW_SEND_FORYOU_CREATOR,DOC_REVIEW_SEND_DEADLINE,DOC_REVIEW_SEND_REVIEW_IDS};
        
        
        //  SET OF FIELDS ON DOC_FILE_REVIEW TABLES
        public final String DOC_FILE_REVIEW_RECV_FILE_ID ="FILE_ID";
        public final String DOC_FILE_REVIEW_RECV_REVIEW_ID ="REVIEW_ID";
        public final String DOC_FILE_REVIEW_RECV_NAME ="NAME";
        public final String DOC_FILE_REVIEW_RECV_FILES ="FILES";    
        public final String DOC_FILE_REVIEW_RECV_PATH_FILE ="PATH_FILE";    
        public final String[] DOC_FILE_REVIEW_RECV_ALL_FIELDS ={DOC_FILE_REVIEW_RECV_REVIEW_ID,DOC_FILE_REVIEW_RECV_NAME,DOC_FILE_REVIEW_RECV_FILES,DOC_FILE_REVIEW_RECV_PATH_FILE};    
        //  SET OF FIELDS ON DOC_FILES_SEND TABLES
        
        
        public final String DOC_FILES_SEND_REVIEW_FILE_ID ="FILE_ID";
        
        public final String DOC_FILES_SEND_REVIEW_REVIEW_ID ="REVIEW_ID";
        public final String DOC_FILES_SEND_REVIEW_NAME ="NAME";
        public final String DOC_FILES_SEND_REVIEW_FILES ="FILES";
        public final String DOC_FILES_SEND_REVIEW_PATH_FILE ="PATH_FILE";    
        public final String[] DOC_FILES_SEND_REVIEW_ALL_FIELDS ={DOC_FILES_SEND_REVIEW_REVIEW_ID,DOC_FILES_SEND_REVIEW_NAME,DOC_FILES_SEND_REVIEW_FILES,DOC_FILES_SEND_REVIEW_PATH_FILE};
                  
      
        
        //  SET OF FIELDS ON DOCSRECV TABLES
        public final String DOCSRECV_DOC_ID="DOC_ID";
        public final String DOCSRECV_FORM_ID="FORM_ID";
        public final String DOCSRECV_LOCALCODE="LOCALCODE";
        public final String DOCSRECV_DOCCODE="DOCCODE";
        public final String DOCSRECV_CREATOR="CREATOR";
        public final String DOCSRECV_COMPLETE="COMPLETE";        
        public final String DOCSRECV_TIMECREATE="TIMECREATE";
        public final String DOCSRECV_LOCALDATE="LOCALDATE";
        public final String DOCSRECV_DOCDATE="DOCDATE";
        public final String DOCSRECV_STOREAGE_ID="STOREAGE_ID";
        public final String DOCSRECV_EXPRESS_ID="EXPRESS_ID";
        public final String DOCSRECV_SECURE_ID="SECURE_ID";
        public final String DOCSRECV_VIA_ID="VIA_ID";
        public final String DOCSRECV_FROM_ID="FROM_ID";
        public final String DOCSRECV_ADDRESS="ADDRESS";
        public final String DOCSRECV_DOCTYPE_ID="DOCTYPE_ID";
        public final String DOCSRECV_ABSTRACT="ABSTRACT";
        public final String DOCSRECV_DESCRIPTION="DESCRIPTION";
        public final String DOCSRECV_SIGNER="SIGNER";
        public final String DOCSRECV_DEADLINE="DEADLINE";
        public final String DOCSRECV_DOSSIERS_ID="DOSSIERS_ID";
        public final String DOCSRECV_WORKFLOW_ID="WORKFLOW_ID";
        public final String DOCSRECV_USER_ID="USER_ID";
        public final String DOCSRECV_STATUS_ID="STATUS_ID";
        public final String DOCSRECV_NUMBERVERSION="NUMBERVERSION";
        public final String DOCSRECV_NUMBERPAGE="NUMBERPAGE";    
        public final String DOCSRECV_BRANCH_ID="BRANCH_ID";
        public final String DOCSRECV_CLASSIFY_ID="CLASSIFY_ID";
        //EXTENSION
         public final String DOCSRECV_STATUS_COLOR="COLOR";
         public final String DOCSRECV_STATUS_NAME="NAME_STATUS";
         public final String DOCSRECV_REVIEW_LEARDER="REVIEW_LEARDER";
    
        public final String[] DOCSRECV_ALL_FIELDS = {DOCSRECV_FORM_ID,DOCSRECV_LOCALCODE,DOCSRECV_DOCCODE,DOCSRECV_USER_ID,DOCSRECV_STATUS_ID,DOCSRECV_TIMECREATE,DOCSRECV_LOCALDATE,DOCSRECV_DOCDATE,DOCSRECV_STOREAGE_ID,DOCSRECV_EXPRESS_ID,DOCSRECV_SECURE_ID,DOCSRECV_VIA_ID,DOCSRECV_FROM_ID,DOCSRECV_ADDRESS,DOCSRECV_DOCTYPE_ID,DOCSRECV_ABSTRACT,DOCSRECV_DESCRIPTION,DOCSRECV_SIGNER,DOCSRECV_DEADLINE,DOCSRECV_DOSSIERS_ID,DOCSRECV_WORKFLOW_ID,DOCSRECV_NUMBERVERSION,DOCSRECV_NUMBERPAGE,DOCSRECV_BRANCH_ID,DOCSRECV_CLASSIFY_ID}; 
        
        //  SET OF FIELDS ON FILESRECV TABLES
        public final String FILESRECV_ID="FILE_ID";
        public final String FILESRECV_DOC_ID="DOC_ID";
        public final String FILESRECV_NAME="REALNAME";
        public final String FILESRECV_FILE="FILENAME";
        public final String FILESRECV_PATH="PATH";
        public final String FILESRECV_FILE_ID_BLOCK="FILE_ID_BLOCK";
    
        public final String[] FILESRECV_ALL_FIELDS = {FILESRECV_DOC_ID,FILESRECV_NAME,FILESRECV_FILE,FILESRECV_PATH,FILESRECV_FILE_ID_BLOCK}; 
                
        //  SET OF FIELDS ON DOCSSEND TABLES
        public final String DOCSSEND_DOC_ID="DOC_ID";
        public final String DOCSSEND_FORM_ID="FORM_ID";
        public final String DOCSSEND_LOCALCODE="LOCALCODE";
        public final String DOCSSEND_DOCCODE="DOCCODE";
        public final String DOCSSEND_CREATOR="CREATOR";
        public final String DOCSSEND_COMPLETE="COMPLETE";        
        public final String DOCSSEND_TIMECREATE="TIMECREATE";
        public final String DOCSSEND_USER_ID="USER_ID";
        public final String DOCSSEND_STATUS_ID="STATUS_ID";
        public final String DOCSSEND_LOCALDATE="LOCALDATE";
        public final String DOCSSEND_DOCDATE="DOCDATE";
        public final String DOCSSEND_STOREAGE_ID="STOREAGE_ID";
        public final String DOCSSEND_EXPRESS_ID="EXPRESS_ID";
        public final String DOCSSEND_SECURE_ID="SECURE_ID";
        public final String DOCSSEND_VIA_ID="VIA_ID";
        public final String DOCSSEND_FROM_ID="FROM_ID";
        public final String DOCSSEND_ADDRESS="ADDRESS";
        public final String DOCSSEND_DOCTYPE_ID="DOCTYPE_ID";
        public final String DOCSSEND_ABSTRACT="ABSTRACT";
        public final String DOCSSEND_DESCRIPTION="DESCRIPTION";
        public final String DOCSSEND_SIGNER="SIGNER";
        public final String DOCSSEND_DEADLINE="DEADLINE";
        public final String DOCSSEND_DOSSIERS_ID="DOSSIERS_ID";
        public final String DOCSSEND_WORKFLOW_ID="WORKFLOW_ID";
        
        //extendtion
        public final String DOCSSEND_STATUS_NAME="NAME_STATUS";
        public final String DOCSSEND_STATUS_COLOR="COLOR";
        public final String DOCSSEND_REFERENT="REFERENT";    
        public final String DOCSSEND_NUMBERVERSION="NUMBERVERSION";
        public final String DOCSSEND_NUMBERPAGE="NUMBERPAGE";    
        public final String DOCSSEND_BRANCH_ID="BRANCH_ID";
        public final String DOCSSEND_CLASSIFY_ID="CLASSIFY_ID";
        public final String DOCSSEND_CREATOR_WHERE="CREATOR_WHERE";    
       public final String[] DOCSSEND_ALL_FIELDS        = {DOCSSEND_FORM_ID,DOCSSEND_LOCALCODE,DOCSSEND_DOCCODE,DOCSSEND_USER_ID,DOCSSEND_STATUS_ID,DOCSSEND_TIMECREATE,DOCSSEND_LOCALDATE,DOCSSEND_DOCDATE,DOCSSEND_STOREAGE_ID,DOCSSEND_EXPRESS_ID,DOCSSEND_SECURE_ID,DOCSSEND_VIA_ID,DOCSSEND_FROM_ID,DOCSSEND_ADDRESS,DOCSSEND_DOCTYPE_ID,DOCSSEND_ABSTRACT,DOCSSEND_DESCRIPTION,DOCSSEND_SIGNER,DOCSSEND_DEADLINE,DOCSSEND_DOSSIERS_ID,DOCSSEND_WORKFLOW_ID,DOCSSEND_REFERENT,DOCSSEND_NUMBERVERSION,DOCSSEND_NUMBERPAGE,DOCSSEND_BRANCH_ID,DOCSSEND_CLASSIFY_ID}; 
       public final String[] DOCSSEND_ALL_FIELDS_UPDATE = {DOCSSEND_FORM_ID,DOCSSEND_LOCALCODE,DOCSSEND_DOCCODE,DOCSSEND_STATUS_ID,DOCSSEND_TIMECREATE,DOCSSEND_LOCALDATE,DOCSSEND_DOCDATE,DOCSSEND_STOREAGE_ID,DOCSSEND_EXPRESS_ID,DOCSSEND_SECURE_ID,DOCSSEND_VIA_ID,DOCSSEND_FROM_ID,DOCSSEND_ADDRESS,DOCSSEND_DOCTYPE_ID,DOCSSEND_ABSTRACT,DOCSSEND_DESCRIPTION,DOCSSEND_SIGNER,DOCSSEND_DEADLINE,DOCSSEND_DOSSIERS_ID,DOCSSEND_WORKFLOW_ID,DOCSSEND_REFERENT,DOCSSEND_NUMBERVERSION,DOCSSEND_NUMBERPAGE,DOCSSEND_BRANCH_ID,DOCSSEND_CLASSIFY_ID}; 
        
        //  SET OF FIELDS ON FILESSEND TABLES
        public final String FILESSEND_ID="FILE_ID";
        public final String FILESSEND_DOC_ID="DOC_ID";
        public final String FILESSEND_NAME="REALNAME";
        public final String FILESSEND_FILE="FILENAME";
        public final String FILESSEND_PATH="PATH";
        public final String FILESSEND_USER_ID="USER_ID";
        public final String FILESSEND_CREATETIME="CREATETIME";
        public final String FILESSEND_PARRENT_FILE_ID ="PARENT_FILE_ID";
        public final String FILESSEND_VERSION ="VERSION";
        public final String FILESSEND_VIEWS ="VIEWS";
        public final String FILESSEND_FILE_TEXT="FILE_TEXT";
        public final String FILESSEND_NUMBER_READED_FILE ="NUMBER_READED_FILE";
        public final String FILESSEND_FILE_ID_BLOCK ="FILE_ID_BLOCK";    
        public final String[] FILESSEND_ALL_FIELDS = {FILESSEND_DOC_ID,FILESSEND_NAME,FILESSEND_FILE,FILESSEND_PATH,FILESSEND_USER_ID,FILESSEND_CREATETIME,FILESSEND_PARRENT_FILE_ID,FILESSEND_VERSION,FILESSEND_FILE_TEXT,FILESSEND_NUMBER_READED_FILE,FILESSEND_FILE_ID_BLOCK};                
       

                   
      
        //  SET OF FIELDS ON DOC_DOSSIERS TABLES
        public final String DOC_DOSSIERS_DOSSIERS_ID ="DOSSIERS_ID";
        public final String DOC_DOSSIERS_DOC_ID ="DOC_ID";
        public final String DOC_DOSSIERS_WORKFLOW_ID ="WORKFLOW_ID";    
        public final String[] DOC_DOSSIERS_ALL_FIELDS = {DOC_DOSSIERS_DOC_ID,DOC_DOSSIERS_WORKFLOW_ID,DOC_DOSSIERS_DOSSIERS_ID};
       
    //  SET OF FIELDS ON DOC_RELATED TABLES
    public final String DOC_RELATED_DOC_ID     ="DOC_RELATED_DOC_ID";
    public final String DOC_RELATED_DOCCODE    ="DOC_RELATED_DOCCODE";
    public final String DOC_RELATED_CREATEDATE ="DOC_RELATED_CREATEDATE";
    public final String DOC_RELATED_WORKFLOW   ="DOC_RELATED_WORKFLOW";
    public final String[] DOC_DOC_RELATED_FIELDS = {DOC_RELATED_DOC_ID,DOC_RELATED_DOCCODE,DOC_RELATED_CREATEDATE,DOC_RELATED_WORKFLOW};
    
}
