package com.dao.cabin;


import com.dao.tasks.DSqlTasks;


public class DSqlCabin extends DSqlTasks{
 
    
    //CABINTYPE
    public final String SQL_CABINTYPE_CHECK_CODE_UPDATE =SELECT + CABINTYPE_CODE +  FROM + TABLE_CABINTYPE + WHERE + CABINTYPE_ID + IN + OPEN + SELECT +  CABINTYPE_ID + FROM +  TABLE_CABINTYPE + WHERE +  CABINTYPE_ID + DIFF + QUESTION + CLOSE + AND +  CABINTYPE_CODE + EQUAL + QUESTION;
    public final String SQL_CABINTYPE_CHECK_ID_EXIST_CABIN = SELECT + CABIN_ID + FROM + TABLE_CABIN + WHERE + CABIN_CABINTYPE_ID + EQUAL + QUESTION + UNION + SELECT + CABINTYPE_ID + FROM + TABLE_CABINTYPE + WHERE + CABINTYPE_PARENT_ID + EQUAL + QUESTION;
    public final String SQL_SELECT_ALL_CABINTYPE = SELECT + STAR + FROM + TABLE_CABINTYPE;
    public final String SQL_CABINTYPE_SELECT_SINGLE_ROW = SELECT + CABINTYPE_ID + COMMA + CABINTYPE_CODE + COMMA + CABINTYPE_NAME + COMMA + CABINTYPE_DESCRIPTION + FROM + TABLE_CABINTYPE + WHERE + CABINTYPE_ID + EQUAL + QUESTION;
    public final String SQL_CABINTYPE_ADD_NEW = INSERT_INTO + TABLE_CABINTYPE + FIELDS(CABINTYPE_ALL_FIELDS,true) + VALUES(CABINTYPE_ALL_FIELDS.length);
    public final String SQL_CABINTYPE_UPDATE = UPDATE + TABLE_CABINTYPE + SET + SETS(CABINTYPE_ALL_FIELDS) + WHERE + CABINTYPE_ID + EQUAL + QUESTION;
    public final String SQL_CABINTYPE_SELECT_CABINTYPE_BY_ID = SELECT + STAR + FROM + TABLE_CABINTYPE + WHERE + CABINTYPE_ID + EQUAL + QUESTION;
    public final String SQL_CABINTYPE_SELECT_CABINTYPE_BY_TYPE = SELECT + STAR + FROM + TABLE_CABINTYPE + WHERE + CABINTYPE_TYPE + EQUAL + QUESTION + AND + CABINTYPE_USER_ID + EQUAL + QUESTION;
    //CABIN USERS
    public final String   SQL_INSERT_CABIN_USERS=INSERT_INTO + TABLE_CABIN_SHARE + FIELDS(CABIN_SHARE_ALL_FIELDS,true) + VALUES(CABIN_SHARE_ALL_FIELDS.length);
    public final String SQL_SELECT_CABIN_BY_TOP=SELECT + MAX(CABIN_ID) + FROM + TABLE_CABIN + WHERE + CABIN_USERS_ID + EQUAL + QUESTION;
    public final String   SQL_SELECT_ALL_USERS_SHAREING=SELECT + TABLE_CABIN + STOP + CABIN_USERS_ID + COMMA + TABLE_USERS + STOP + USERS_FULLNAME +  FROM +  TABLE_CABIN +  LEFT_JOIN +  TABLE_CABIN_SHARE +  ON +  TABLE_CABIN + STOP + CABIN_SHARE_CABIN_ID + EQUAL + TABLE_CABIN_SHARE + STOP + CABIN_SHARE_CABIN_ID +  LEFT_JOIN +  TABLE_USERS +  ON +  TABLE_USERS + STOP + USERS_USER_ID + EQUAL + TABLE_CABIN + STOP + CABIN_USERS_ID +  WHERE +  TABLE_CABIN_SHARE + STOP + CABIN_SHARE_USER_ID + EQUAL + QUESTION;
    public final String  SQL_SELECT_USER_SHARE_FOR_ME=SELECT + TABLE_USERS + STOP + USERS_USER_ID + COMMA + TABLE_USERS + STOP + USERS_FULLNAME + FROM + TABLE_CABIN + LEFT_JOIN + TABLE_USERS + ON + TABLE_USERS + STOP + USERS_USER_ID + EQUAL + TABLE_CABIN + STOP + CABIN_USERS_ID + WHERE + TABLE_CABIN + STOP + CABIN_ID + IN + OPEN + SELECT + CABIN_SHARE_CABIN_ID + FROM + TABLE_CABIN_SHARE + WHERE + CABIN_SHARE_USER_ID + EQUAL + QUESTION + CLOSE + ORDER_BY + CABIN_SHARE_USER_ID;
    
    //CABINTYPE
    public final String SQL_SELECT_ALL_TYPE=SELECT + STAR + COMMA + TABLE_USERS + STOP + USERS_FULLNAME + FROM + TABLE_CABIN + LEFT_JOIN + TABLE_USERS + ON + TABLE_USERS + STOP + USERS_USER_ID + EQUAL + TABLE_CABIN + STOP + CABIN_USERS_ID;
    public final String SQL_CABINTYPE_SELECT_ALL_CABINTYPE = SELECT + STAR + FROM + TABLE_CABINTYPE + WHERE +  CABINTYPE_TYPE + EQUAL + QUESTION;
    public final String  SQL_SELECT_USERS_RECV=SELECT + TABLE_CABIN_SHARE + STOP + CABIN_SHARE_USER_ID + COMMA + TABLE_USERS + STOP + USERS_FULLNAME + FROM + TABLE_CABIN_SHARE + LEFT_JOIN + TABLE_USERS + ON + TABLE_USERS + STOP + USERS_USER_ID + EQUAL + TABLE_CABIN_SHARE + STOP + CABIN_SHARE_USER_ID + WHERE + TABLE_CABIN_SHARE + STOP + CABIN_SHARE_CABIN_ID + EQUAL + QUESTION;
    
    public final String SQL_SELECT_ALL_CABIN_UNION_CABINTYPE="select id,null as users_id,name,null as description,null as timecreate,parent_id as cabintype_id,null as filestore, name as realname,type,null as capacity,null as fullname,department_id,1 as typefile FROM CABINTYPE WHERE TYPE=? ";
    public final String SQL_SELECT_ALL_CABIN_UNION_CABIN="select cabin.*,USERS.fullname,USERS.department_id,0 as typefile from cabin\n" + 
    "LEFT JOIN USERS ON USERS.USER_ID=CABIN.USERS_ID \n" + 
    " where cabin.type=? ";

    
    public final String SQL_CABIN_CHECK_FILESTORE = SELECT + STAR + FROM + TABLE_CABIN + WHERE + CABIN_FILESTORE + EQUAL + QUESTION;

    public final String SQL_SELECT_BY_ID=SELECT + STAR + FROM + TABLE_CABIN + WHERE + CABIN_ID + EQUAL + QUESTION ;
    
    public final String SQL_INSERT_CABIN = INSERT_INTO + TABLE_CABIN + FIELDS(CABIN_ALL_FIELDS,true) + VALUES(CABIN_ALL_FIELDS.length);
    public final String SQL_UPDATE_CABIN = UPDATE + TABLE_CABIN + SET + SETS(CABIN_ALL_FIELDS) + WHERE + CABIN_ID + EQUAL + QUESTION;
}
