package com.dao.calendar.agenda;


import com.dao.cabin.DSqlCabin;


public class DSqlMyagenda extends DSqlCabin{
    //CALEDAR    
    public final String SQL_SELECT_ALL_CALENDAR_FROMDATE_TO_TODATE=    SELECT + TABLE_CALENDAR + STOP +STAR + COMMA + TABLE_USERS + STOP + USERS_FULLNAME + FROM + TABLE_CALENDAR +     LEFT_JOIN + TABLE_USERS + ON + TABLE_CALENDAR + STOP + CALENDA_USER_ID + EQUAL + TABLE_USERS + STOP + USERS_USER_ID +         WHERE + CALENDA_TIMEEVENT + ">=" +QUESTION +  AND +  CALENDA_TIMEEVENT + "<" + QUESTION +     AND + TABLE_CALENDAR + STOP + CALENDA_TYPE + EQUAL + QUESTION;
    public final String SQL_CALENDAR_UPDATE = UPDATE + TABLE_CALENDAR+ SET + SETS(CALENDAR_ALL_FIELDS) + WHERE + CALENDA_ID + EQUAL + QUESTION;
    public final String SQL_CALENDAR_ADD_NEW = INSERT_INTO + TABLE_CALENDAR + FIELDS(CALENDAR_ALL_FIELDS,true) + VALUES(CALENDAR_ALL_FIELDS.length);
    public final String SQL_SELECT_CALENDAR_BY_ID=SELECT + STAR + FROM + TABLE_CALENDAR + WHERE + CALENDA_ID + EQUAL + QUESTION;
    public final String SQL_SELECT_CALENDA_AT_MAIN=SELECT + STAR + FROM + TABLE_CALENDAR + WHERE + CALENDA_TIMEEVENT + ">=" +QUESTION +  AND +  CALENDA_TIMEEVENT + "<" + QUESTION + AND + CALENDA_TYPE + EQUAL + QUESTION;
    //CALEDAR    
     public final String SQL_SELECT_ALL_CALENDAR_MEETING_FROMDATE_TO_TODATE=    SELECT + TABLE_CALENDAR_MEETING + STOP +STAR + COMMA + TABLE_USERS + STOP + USERS_FULLNAME + FROM + TABLE_CALENDAR_MEETING +     LEFT_JOIN + TABLE_USERS + ON + TABLE_CALENDAR_MEETING + STOP + CALENDA_USER_ID + EQUAL + TABLE_USERS + STOP + USERS_USER_ID +         WHERE + CALENDAR_MEETING_TIMEEVENT + ">=" +QUESTION +  AND +  CALENDAR_MEETING_TIMEEVENT + "<" + QUESTION ;
     public final String SQL_CALENDAR_MEETING_UPDATE = UPDATE + TABLE_CALENDAR_MEETING+ SET + SETS(CALENDAR_MEETINGR_ALL_FIELDS) + WHERE + CALENDA_ID + EQUAL + QUESTION;
     public final String SQL_CALENDAR_MEETING_ADD_NEW = INSERT_INTO + TABLE_CALENDAR_MEETING + FIELDS(CALENDAR_MEETINGR_ALL_FIELDS,true) + VALUES(CALENDAR_MEETINGR_ALL_FIELDS.length);
     public final String SQL_SELECT_CALENDAR_MEETING_BY_ID=SELECT + STAR + FROM + TABLE_CALENDAR_MEETING + WHERE + CALENDAR_MEETING_MEETING_ID + EQUAL + QUESTION;
     public final String SQL_SELECT_CALENDA_MEETING_AT_MAIN=SELECT + STAR + FROM + TABLE_CALENDAR_MEETING + WHERE + CALENDAR_MEETING_TIMEEVENT + ">=" +QUESTION +  AND +  CALENDAR_MEETING_TIMEEVENT + "<" + QUESTION;
  //CALEDAR xe   
   public final String SQL_SELECT_ALL_CALENDAR_XE_FROMDATE_TO_TODATE=    SELECT + TABLE_CALENDAR_XE + STOP +STAR + COMMA + TABLE_USERS + STOP + USERS_FULLNAME + FROM + TABLE_CALENDAR_XE +     LEFT_JOIN + TABLE_USERS + ON + TABLE_CALENDAR_XE + STOP + CALENDA_USER_ID + EQUAL + TABLE_USERS + STOP + USERS_USER_ID +         WHERE + CALENDAR_XE_TIMEEVENT + ">=" +QUESTION +  AND +  CALENDAR_XE_TIMEEVENT + "<" + QUESTION ;
   public final String SQL_CALENDAR_XE_UPDATE = UPDATE + TABLE_CALENDAR_XE+ SET + SETS(CALENDAR_XER_ALL_FIELDS) + WHERE + CALENDAR_XE_MEETING_ID + EQUAL + QUESTION;
   public final String SQL_CALENDAR_XE_ADD_NEW = INSERT_INTO + TABLE_CALENDAR_XE + FIELDS(CALENDAR_XER_ALL_FIELDS,true) + VALUES(CALENDAR_XER_ALL_FIELDS.length);
   public final String SQL_SELECT_CALENDAR_XE_BY_ID=SELECT + STAR + FROM + TABLE_CALENDAR_XE + WHERE + CALENDAR_XE_MEETING_ID + EQUAL + QUESTION;
   public final String SQL_SELECT_CALENDAR_MEETING_AT_MAIN=SELECT + STAR + FROM + TABLE_CALENDAR_XE + WHERE + CALENDAR_XE_TIMEEVENT + ">=" +QUESTION +  AND +  CALENDAR_XE_TIMEEVENT + "<" + QUESTION;
}
